apiVersion: v1
kind: Service
metadata:
  name: grpc-ping
  labels:
    app: grpc-ping
    service: grpc-ping
spec:
  type: NodePort
  ports:
  - name: grpc-ping
    port: 8080
    targetPort: 8080
  selector:
    app: grpc-ping
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-ping
      version: v0.0.1
  template:
    metadata:
      labels:
        app: grpc-ping
        version: v0.0.1
    spec:
      containers:
      - image: ssingh3339/grpc-ping:latest
        imagePullPolicy: IfNotPresent
        name: grpc-ping
        ports:
        - containerPort: 8080
        resources: 
            limits: 
              cpu: ".5"
              memory: 100Mi
            requests: 
              cpu: ".25"
              memory: 50Mi