// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: message.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageProcessorClient is the client API for MessageProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageProcessorClient interface {
	ProcessMessages(ctx context.Context, in *MessagePayload, opts ...grpc.CallOption) (*Ack, error)
}

type messageProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageProcessorClient(cc grpc.ClientConnInterface) MessageProcessorClient {
	return &messageProcessorClient{cc}
}

func (c *messageProcessorClient) ProcessMessages(ctx context.Context, in *MessagePayload, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/proto.MessageProcessor/ProcessMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageProcessorServer is the server API for MessageProcessor service.
// All implementations must embed UnimplementedMessageProcessorServer
// for forward compatibility
type MessageProcessorServer interface {
	ProcessMessages(context.Context, *MessagePayload) (*Ack, error)
	mustEmbedUnimplementedMessageProcessorServer()
}

// UnimplementedMessageProcessorServer must be embedded to have forward compatible implementations.
type UnimplementedMessageProcessorServer struct {
}

func (UnimplementedMessageProcessorServer) ProcessMessages(context.Context, *MessagePayload) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMessages not implemented")
}
func (UnimplementedMessageProcessorServer) mustEmbedUnimplementedMessageProcessorServer() {}

// UnsafeMessageProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageProcessorServer will
// result in compilation errors.
type UnsafeMessageProcessorServer interface {
	mustEmbedUnimplementedMessageProcessorServer()
}

func RegisterMessageProcessorServer(s grpc.ServiceRegistrar, srv MessageProcessorServer) {
	s.RegisterService(&MessageProcessor_ServiceDesc, srv)
}

func _MessageProcessor_ProcessMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagePayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageProcessorServer).ProcessMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MessageProcessor/ProcessMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageProcessorServer).ProcessMessages(ctx, req.(*MessagePayload))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageProcessor_ServiceDesc is the grpc.ServiceDesc for MessageProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MessageProcessor",
	HandlerType: (*MessageProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessMessages",
			Handler:    _MessageProcessor_ProcessMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
